version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/velvetbloom

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080

  admin:
      build:
        context: ./admin
        dockerfile: Dockerfile
      ports:
        - "3001:80"
      environment:
        - NEXT_PUBLIC_BACKEND_URL=http://backend:8080

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
